name: med_health_v1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: any
  animate_do: any
  liquid_pull_to_refresh: ^3.0.1
  google_fonts: ^6.1.0
  badges: ^3.1.2
  persistent_bottom_nav_bar_v2: ^4.2.8
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  image_picker: ^1.0.6
  font_awesome_flutter: ^10.7.0
  #awesome_notifications: ^0.9.2
  percent_indicator: ^4.2.3
  flutter_slidable: ^3.0.1
  ionicons: ^0.2.2
  curved_navigation_bar: ^1.0.3
  isar_flutter_libs: ^3.1.0+1
  isar_generator: ^3.1.0+1
  flutter_heatmap_calendar: ^1.0.5
  provider: ^6.1.1
  dot_navigation_bar: ^1.0.2
  smooth_page_indicator: ^1.1.0
  the_apple_sign_in: ^1.1.1
  bloc: ^8.1.2
  http: ^1.1.2
  flutter_bloc: ^8.1.3
  url_launcher: ^6.2.2
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  path_provider: ^2.1.2
  hive: ^2.2.3
  isar: ^3.1.0+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  health: ^9.0.1
  shimmer_animation: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  #isar_generator: ^3.1.0+1
  build_runner: any
  analyzer: 5.13.0
 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/appicon_dark.png"
  min_sdk_android: 21
flutter_app_name:
  name: "App Care+"
  

flutter:

  
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - lib/components/image/image1.png
    - lib/components/image/health/diet.png
    - lib/components/image/health/vr-fitness.png
    
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
